version: '3.4'

x-healthcheck: &healthcheck
  test: [ "CMD", "curl", "-sf", "http://localhost:8545" ]
  interval: 5s
  timeout: 5s
  retries: 3
  start_period: 30s

services:
  op-geth:
    image: mantle-op-geth:v0.5.0
    extra_hosts:
      - "host.docker.internal:host-gateway"
    entrypoint: ["exec", "geth"]
    command: 
      - --datadir=/db
      - --verbosity=3
      - --port=30300
      - --http
      - --http.corsdomain=*
      - --http.vhosts=*
      - --http.addr=0.0.0.0
      - --http.port=8545
      - --http.api=web3,eth,debug,txpool,net
      - --ws
      - --ws.addr=0.0.0.0
      - --ws.port=8546
      - --ws.origins=*
      - --ws.api=web3,eth,debug,txpool,net
      - --syncmode=full
      - --maxpeers=0
      - --networkid=5003
      - --rpc.allow-unprotected-txs
      - --authrpc.addr=0.0.0.0
      - --authrpc.port=8551
      - --authrpc.vhosts=*
      - --authrpc.jwtsecret=/secret/jwt_secret_txt
      - --pprof
      - --pprof.addr=0.0.0.0
      - --pprof.port=6060
      - --gcmode=archive
      - --metrics
      - --metrics.addr=0.0.0.0
      - --metrics.port=9001
    volumes:
      - ./sepolia/secret:/secret/
      - ./data/geth:/db/geth/
    ports:
      - ${VERIFIER_HTTP_PORT:-8545}:8545
      - ${VERIFIER_WS_PORT:-8546}:8546
      - ${VERIFIER_AUTH_PORT:-8551}:8551
  op-node:
    image: mantle-op-geth:v0.5.0
    depends_on:
      - op-geth
    env_file:
      - ./sepolia/envs/node.env
    volumes:
      - ./sepolia/secret:/secret
      - ./sepolia/rollup.json:/config/rollup.json
    environment:
      OP_NODE_L1_ETH_RPC: 'wss://eth-sepolia.g.alchemy.com/v2/WCsU3YbVKyCNkr99aTxumpV5yJOtlsXT'
      OP_NODE_L2_ENGINE_RPC: 'http://op-geth:8551'
      OP_NODE_L2_ENGINE_AUTH: /secret/jwt_secret_txt
      OP_NODE_ROLLUP_CONFIG: '/config/rollup.json'
      OP_NODE_P2P_PRIV_PATH: /secret/p2p_node_key_txt
      OP_NODE_RETRIEVER_SOCKET: 10.45.114.221:32000
      OP_NODE_GRAPH_PROVIDER: http://10.45.86.238:8000/subgraphs/name/datalayr
      OP_NODE_L2_BACKUP_UNSAFE_SYNC_RPC: http://10.45.93.51:8545
      OP_NODE_P2P_STATIC: '/ip4/10.47.68.158/tcp/9003/p2p/16Uiu2HAmMMdS2hQigLBUjXVucQ9n3Ce4p81e58uiS5Vf32sR6yQc'
    ports:
      - ${NODE_RPC_PORT:-9545}:8545
      - ${NODE_P2P_PORT:-9003}:9003